# Meson cross file used to build the qboot (bios-microvm) firmware when the
# build host is not x86.  qboot.rom is shipped in the arch:all
# qemu-system-data package, so it has to be produced on every architecture.
[binaries]
c = 'i686-linux-gnu-gcc'
ar = 'i686-linux-gnu-ar'
strip = 'i686-linux-gnu-strip'
objcopy = 'i686-linux-gnu-objcopy'

[host_machine]
system = 'linux'
cpu_family = 'x86'
cpu = 'i686'
endian = 'little'
